### ISSUE TITLE
Notify illegal access to authorized user : Feature Request

### ISSUE THREAD

**Issue by surajkothawade** [fresearchgroup/drupal-logger#8]
Current event_log module does not notify the owner of an account about fraudulent login attempts to his account but blocks the user's account temporarily after 5 incorrect attempts. 
A feature that will notify authorised user about the 3 consecutive illegal access to his/her account is required.This feature should send an email to user's email provided at the time of account creation ,to notify when 3 password fails occur . Also sending the IP address from which failure has occurred can aid tracing the intruder.

**Comment by sumbb** [comment]
Following commit closes this issue 
 SHA : a73af90447d7a4cd9d0e5464fc2b3d5365f56245
